import type { Locale } from '@/i18n/types';

export type OnboardingCopy = {
  languageName: string;
  eyebrow: string;
  welcomeTitle: string;
  purposeLines: readonly string[];
  travelLine: string;
  startCta: string;
  languageTitle: string;
  languageSubtitle: string;
  continueCta: string;
  authTitle: string;
  authSubtitle: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  loginCta: string;
  registerCta: string;
  switchToLogin: string;
  switchToRegister: string;
  errorTitle: string;
  successTitle: string;
  weakPassword: string;
  confirmEmail: string;
  genericLoginError: string;
  genericRegisterError: string;
};

export const ONBOARDING_LANGUAGE_ORDER: Locale[] = [
  'tr',
  'en',
  'de',
  'fr',
  'es',
  'it',
  'ar',
  'ru',
];

export const ONBOARDING_COPY: Record<Locale, OnboardingCopy> = {
  tr: {
    languageName: 'Türkçe',
    eyebrow: 'Kişisel stil atölyeniz',
    welcomeTitle: 'Stylove’a hoş geldiniz',
    purposeLines: [
      'Nereye gideceğinizi yazın.',
      'Gardırobunuzdan size özel kombinler oluşturulsun,',
      'seyahatinize uygun valiz hazırlansın.',
    ],
    travelLine: 'Travel ve valiz hazırlığı, stilinizle birlikte planlanır.',
    startCta: 'Devam et',
    languageTitle: 'Dilinizi seçin',
    languageSubtitle: 'Onboarding ve hesap akışı seçtiğiniz dilde devam eder.',
    continueCta: 'Hesaba devam et',
    authTitle: 'Hesabınıza giriş yapın',
    authSubtitle: 'Gardırobunuz ve stilleriniz yalnızca kendi hesabınızda saklanır.',
    emailPlaceholder: 'E-posta',
    passwordPlaceholder: 'Şifre',
    loginCta: 'Giriş yap',
    registerCta: 'Hesap oluştur',
    switchToLogin: 'Zaten hesabınız var mı? Giriş yapın',
    switchToRegister: 'Hesabınız yok mu? Hesap oluşturun',
    errorTitle: 'Hesap',
    successTitle: 'Başarılı',
    weakPassword: 'Şifre en az 6 karakter olmalıdır.',
    confirmEmail: 'Hesabınız oluşturuldu. Lütfen e-posta adresinizi doğrulayın.',
    genericLoginError: 'Giriş yapılamadı. E-posta ve şifrenizi kontrol edin.',
    genericRegisterError: 'Hesap oluşturulamadı. Lütfen tekrar deneyin.',
  },
  en: {
    languageName: 'English',
    eyebrow: 'Your private style atelier',
    welcomeTitle: 'Welcome to Stylove',
    purposeLines: [
      'Tell us where you are going.',
      'Personal looks will be styled from your wardrobe,',
      'and a suitcase will be prepared for your trip.',
    ],
    travelLine: 'Travel and packing are planned around your style.',
    startCta: 'Continue',
    languageTitle: 'Choose your language',
    languageSubtitle: 'Onboarding and account setup will continue in your selected language.',
    continueCta: 'Continue to account',
    authTitle: 'Sign in to your account',
    authSubtitle: 'Your wardrobe and looks stay only inside your own account.',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginCta: 'Log in',
    registerCta: 'Create account',
    switchToLogin: 'Already have an account? Log in',
    switchToRegister: 'No account yet? Create one',
    errorTitle: 'Account',
    successTitle: 'Success',
    weakPassword: 'Password must be at least 6 characters.',
    confirmEmail: 'Your account has been created. Please verify your email address.',
    genericLoginError: 'Could not log in. Check your email and password.',
    genericRegisterError: 'Could not create your account. Please try again.',
  },
  de: {
    languageName: 'Deutsch',
    eyebrow: 'Ihr privates Stilatelier',
    welcomeTitle: 'Willkommen bei Stylove',
    purposeLines: [
      'Schreiben Sie, wohin Sie gehen.',
      'Aus Ihrer Garderobe entstehen persönliche Looks,',
      'und der passende Koffer wird für Ihre Reise vorbereitet.',
    ],
    travelLine: 'Reise und Kofferplanung folgen Ihrem Stil.',
    startCta: 'Weiter',
    languageTitle: 'Sprache wählen',
    languageSubtitle: 'Onboarding und Kontoerstellung werden in der gewählten Sprache fortgesetzt.',
    continueCta: 'Zum Konto',
    authTitle: 'Bei Ihrem Konto anmelden',
    authSubtitle: 'Ihre Garderobe und Looks bleiben nur in Ihrem eigenen Konto.',
    emailPlaceholder: 'E-Mail',
    passwordPlaceholder: 'Passwort',
    loginCta: 'Einloggen',
    registerCta: 'Konto erstellen',
    switchToLogin: 'Schon ein Konto? Einloggen',
    switchToRegister: 'Noch kein Konto? Konto erstellen',
    errorTitle: 'Konto',
    successTitle: 'Erfolgreich',
    weakPassword: 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    confirmEmail: 'Ihr Konto wurde erstellt. Bitte bestätigen Sie Ihre E-Mail-Adresse.',
    genericLoginError: 'Anmeldung nicht möglich. Prüfen Sie E-Mail und Passwort.',
    genericRegisterError: 'Konto konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',
  },
  fr: {
    languageName: 'Français',
    eyebrow: 'Votre atelier de style privé',
    welcomeTitle: 'Bienvenue sur Stylove',
    purposeLines: [
      'Écrivez où vous allez.',
      'Des tenues personnalisées seront créées depuis votre garde-robe,',
      'et une valise adaptée à votre voyage sera préparée.',
    ],
    travelLine: 'Le voyage et la valise sont pensés autour de votre style.',
    startCta: 'Continuer',
    languageTitle: 'Choisissez votre langue',
    languageSubtitle: 'L’onboarding et le compte continueront dans la langue choisie.',
    continueCta: 'Continuer vers le compte',
    authTitle: 'Connectez-vous à votre compte',
    authSubtitle: 'Votre garde-robe et vos looks restent uniquement dans votre compte.',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Mot de passe',
    loginCta: 'Se connecter',
    registerCta: 'Créer un compte',
    switchToLogin: 'Déjà un compte ? Se connecter',
    switchToRegister: 'Pas encore de compte ? Créer un compte',
    errorTitle: 'Compte',
    successTitle: 'Succès',
    weakPassword: 'Le mot de passe doit contenir au moins 6 caractères.',
    confirmEmail: 'Votre compte a été créé. Veuillez vérifier votre e-mail.',
    genericLoginError: 'Connexion impossible. Vérifiez votre e-mail et votre mot de passe.',
    genericRegisterError: 'Impossible de créer le compte. Veuillez réessayer.',
  },
  es: {
    languageName: 'Español',
    eyebrow: 'Su atelier privado de estilo',
    welcomeTitle: 'Bienvenido a Stylove',
    purposeLines: [
      'Escriba adónde va.',
      'Se crearán looks personalizados desde su armario,',
      'y se preparará una maleta adecuada para su viaje.',
    ],
    travelLine: 'El viaje y la maleta se planifican alrededor de su estilo.',
    startCta: 'Continuar',
    languageTitle: 'Elija su idioma',
    languageSubtitle: 'El onboarding y la cuenta continuarán en el idioma elegido.',
    continueCta: 'Continuar a la cuenta',
    authTitle: 'Inicie sesión en su cuenta',
    authSubtitle: 'Su armario y sus looks permanecen solo en su propia cuenta.',
    emailPlaceholder: 'Correo electrónico',
    passwordPlaceholder: 'Contraseña',
    loginCta: 'Iniciar sesión',
    registerCta: 'Crear cuenta',
    switchToLogin: '¿Ya tiene cuenta? Iniciar sesión',
    switchToRegister: '¿No tiene cuenta? Crear una',
    errorTitle: 'Cuenta',
    successTitle: 'Éxito',
    weakPassword: 'La contraseña debe tener al menos 6 caracteres.',
    confirmEmail: 'Su cuenta fue creada. Verifique su correo electrónico.',
    genericLoginError: 'No se pudo iniciar sesión. Revise su correo y contraseña.',
    genericRegisterError: 'No se pudo crear la cuenta. Inténtelo de nuevo.',
  },
  it: {
    languageName: 'Italiano',
    eyebrow: 'Il suo atelier di stile privato',
    welcomeTitle: 'Benvenuto in Stylove',
    purposeLines: [
      'Scriva dove sta andando.',
      'Dal suo guardaroba nasceranno look personalizzati,',
      'e una valigia adatta al viaggio sarà preparata.',
    ],
    travelLine: 'Viaggio e valigia seguono il suo stile.',
    startCta: 'Continua',
    languageTitle: 'Scelga la lingua',
    languageSubtitle: 'Onboarding e account continueranno nella lingua scelta.',
    continueCta: 'Vai all’account',
    authTitle: 'Acceda al suo account',
    authSubtitle: 'Guardaroba e look restano solo nel suo account.',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Password',
    loginCta: 'Accedi',
    registerCta: 'Crea account',
    switchToLogin: 'Ha già un account? Acceda',
    switchToRegister: 'Non ha un account? Lo crei',
    errorTitle: 'Account',
    successTitle: 'Successo',
    weakPassword: 'La password deve contenere almeno 6 caratteri.',
    confirmEmail: 'Il suo account è stato creato. Verifichi l’e-mail.',
    genericLoginError: 'Accesso non riuscito. Controlli e-mail e password.',
    genericRegisterError: 'Impossibile creare l’account. Riprovi.',
  },
  ar: {
    languageName: 'العربية',
    eyebrow: 'مشغل أسلوبك الخاص',
    welcomeTitle: 'مرحباً بك في Stylove',
    purposeLines: [
      'اكتب إلى أين ستذهب.',
      'سننشئ إطلالات مخصصة من خزانتك،',
      'ونحضّر حقيبة مناسبة لرحلتك.',
    ],
    travelLine: 'السفر والحقيبة يُخططان حول أسلوبك.',
    startCta: 'متابعة',
    languageTitle: 'اختر اللغة',
    languageSubtitle: 'سيستمر التعريف والحساب باللغة التي تختارها.',
    continueCta: 'المتابعة إلى الحساب',
    authTitle: 'سجّل الدخول إلى حسابك',
    authSubtitle: 'تبقى خزانتك وإطلالاتك داخل حسابك فقط.',
    emailPlaceholder: 'البريد الإلكتروني',
    passwordPlaceholder: 'كلمة المرور',
    loginCta: 'تسجيل الدخول',
    registerCta: 'إنشاء حساب',
    switchToLogin: 'لديك حساب؟ سجّل الدخول',
    switchToRegister: 'ليس لديك حساب؟ أنشئ حساباً',
    errorTitle: 'الحساب',
    successTitle: 'تم بنجاح',
    weakPassword: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    confirmEmail: 'تم إنشاء حسابك. يرجى تأكيد بريدك الإلكتروني.',
    genericLoginError: 'تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.',
    genericRegisterError: 'تعذر إنشاء الحساب. حاول مرة أخرى.',
  },
  ru: {
    languageName: 'Русский',
    eyebrow: 'Ваше личное ателье стиля',
    welcomeTitle: 'Добро пожаловать в Stylove',
    purposeLines: [
      'Напишите, куда вы собираетесь.',
      'Мы создадим персональные образы из вашего гардероба,',
      'и подготовим чемодан для вашей поездки.',
    ],
    travelLine: 'Путешествие и чемодан планируются вокруг вашего стиля.',
    startCta: 'Продолжить',
    languageTitle: 'Выберите язык',
    languageSubtitle: 'Онбординг и вход продолжатся на выбранном языке.',
    continueCta: 'Перейти к аккаунту',
    authTitle: 'Войдите в аккаунт',
    authSubtitle: 'Ваш гардероб и образы остаются только в вашем аккаунте.',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Пароль',
    loginCta: 'Войти',
    registerCta: 'Создать аккаунт',
    switchToLogin: 'Уже есть аккаунт? Войти',
    switchToRegister: 'Нет аккаунта? Создать',
    errorTitle: 'Аккаунт',
    successTitle: 'Готово',
    weakPassword: 'Пароль должен содержать не менее 6 символов.',
    confirmEmail: 'Ваш аккаунт создан. Подтвердите e-mail.',
    genericLoginError: 'Не удалось войти. Проверьте e-mail и пароль.',
    genericRegisterError: 'Не удалось создать аккаунт. Попробуйте ещё раз.',
  },
};
