import type { Locale } from '@/i18n/types';

export type OnboardingSlideCopy = {
  title: string;
  subtitle: string;
};

export type OnboardingCopy = {
  languageName: string;
  splashSubtitle: string;
  slides: readonly OnboardingSlideCopy[];
  continueCta: string;
  skipCta: string;
  authWelcomeTitle: string;
  authWelcomeSubtitle: string;
  continueWithEmail: string;
  continueWithGoogle: string;
  continueWithApple: string;
  loginLink: string;
  registerLink: string;
  languageLabel: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  loginCta: string;
  registerCta: string;
  switchToLogin: string;
  switchToRegister: string;
  socialComingSoon: string;
  errorTitle: string;
  successTitle: string;
  weakPassword: string;
  confirmEmail: string;
};

export const ONBOARDING_LANGUAGE_ORDER: Locale[] = [
  'tr',
  'en',
  'de',
  'fr',
  'es',
  'it',
  'ar',
  'ru',
];

export const ONBOARDING_COPY: Record<Locale, OnboardingCopy> = {
  tr: {
    languageName: 'Türkçe',
    splashSubtitle: 'Kişisel stilin, her zaman yanında.',
    slides: [
      { title: 'Stilini keşfet.', subtitle: 'Gardırobundan özel kombinler.' },
      { title: 'Gardırobunu yeniden yorumla.', subtitle: 'Her parça, sizin imzanız.' },
      { title: 'Her gün daha rafine görün.', subtitle: 'Sakin, zarif, size özel.' },
    ],
    continueCta: 'Devam Et',
    skipCta: 'Atla',
    authWelcomeTitle: 'Hoş geldiniz',
    authWelcomeSubtitle: 'Stiliniz sizi bekliyor.',
    continueWithEmail: 'E-posta ile devam et',
    continueWithGoogle: 'Google ile devam et',
    continueWithApple: 'Apple ile devam et',
    loginLink: 'Giriş yap',
    registerLink: 'Hesap oluştur',
    languageLabel: 'Dil',
    emailPlaceholder: 'E-posta',
    passwordPlaceholder: 'Şifre',
    loginCta: 'Giriş yap',
    registerCta: 'Hesap oluştur',
    switchToLogin: 'Zaten hesabınız var mı? Giriş yapın',
    switchToRegister: 'Hesabınız yok mu? Hesap oluşturun',
    socialComingSoon: 'Bu giriş yöntemi yakında kullanılabilir olacak.',
    errorTitle: 'Hesap',
    successTitle: 'Başarılı',
    weakPassword: 'Şifre en az 6 karakter olmalıdır.',
    confirmEmail: 'Hesabınız oluşturuldu. Lütfen e-posta adresinizi doğrulayın.',
  },
  en: {
    languageName: 'English',
    splashSubtitle: 'Your personal style, always with you.',
    slides: [
      { title: 'Discover your style.', subtitle: 'Curated looks from your wardrobe.' },
      { title: 'Reimagine your wardrobe.', subtitle: 'Every piece, intentionally yours.' },
      { title: 'Look more refined every day.', subtitle: 'Calm, elegant, unmistakably you.' },
    ],
    continueCta: 'Continue',
    skipCta: 'Skip',
    authWelcomeTitle: 'Welcome',
    authWelcomeSubtitle: 'Your style journey begins here.',
    continueWithEmail: 'Continue with Email',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    loginLink: 'Log in',
    registerLink: 'Create account',
    languageLabel: 'Language',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginCta: 'Log in',
    registerCta: 'Create account',
    switchToLogin: 'Already have an account? Log in',
    switchToRegister: 'No account yet? Create one',
    socialComingSoon: 'This sign-in option will be available soon.',
    errorTitle: 'Account',
    successTitle: 'Success',
    weakPassword: 'Password must be at least 6 characters.',
    confirmEmail: 'Your account has been created. Please verify your email address.',
  },
  de: {
    languageName: 'Deutsch',
    splashSubtitle: 'Ihr persönlicher Stil, immer an Ihrer Seite.',
    slides: [
      { title: 'Entdecken Sie Ihren Stil.', subtitle: 'Kuratierte Looks aus Ihrer Garderobe.' },
      { title: 'Interpretieren Sie Ihre Garderobe neu.', subtitle: 'Jedes Stück, bewusst Ihr.' },
      { title: 'Jeden Tag raffinierter wirken.', subtitle: 'Ruhig, elegant, ganz Ihr.' },
    ],
    continueCta: 'Weiter',
    skipCta: 'Überspringen',
    authWelcomeTitle: 'Willkommen',
    authWelcomeSubtitle: 'Ihre Stilreise beginnt hier.',
    continueWithEmail: 'Mit E-Mail fortfahren',
    continueWithGoogle: 'Mit Google fortfahren',
    continueWithApple: 'Mit Apple fortfahren',
    loginLink: 'Anmelden',
    registerLink: 'Konto erstellen',
    languageLabel: 'Sprache',
    emailPlaceholder: 'E-Mail',
    passwordPlaceholder: 'Passwort',
    loginCta: 'Einloggen',
    registerCta: 'Konto erstellen',
    switchToLogin: 'Schon ein Konto? Einloggen',
    switchToRegister: 'Noch kein Konto? Konto erstellen',
    socialComingSoon: 'Diese Anmeldung ist bald verfügbar.',
    errorTitle: 'Konto',
    successTitle: 'Erfolgreich',
    weakPassword: 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    confirmEmail: 'Ihr Konto wurde erstellt. Bitte bestätigen Sie Ihre E-Mail-Adresse.',
  },
  fr: {
    languageName: 'Français',
    splashSubtitle: 'Votre style personnel, toujours avec vous.',
    slides: [
      { title: 'Découvrez votre style.', subtitle: 'Des tenues choisies dans votre garde-robe.' },
      { title: 'Réinterprétez votre garde-robe.', subtitle: 'Chaque pièce, intentionnellement vôtre.' },
      { title: 'Paraissez plus raffinée chaque jour.', subtitle: 'Calme, élégant, uniquement vous.' },
    ],
    continueCta: 'Continuer',
    skipCta: 'Passer',
    authWelcomeTitle: 'Bienvenue',
    authWelcomeSubtitle: 'Votre parcours style commence ici.',
    continueWithEmail: 'Continuer avec l’e-mail',
    continueWithGoogle: 'Continuer avec Google',
    continueWithApple: 'Continuer avec Apple',
    loginLink: 'Se connecter',
    registerLink: 'Créer un compte',
    languageLabel: 'Langue',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Mot de passe',
    loginCta: 'Se connecter',
    registerCta: 'Créer un compte',
    switchToLogin: 'Déjà un compte ? Se connecter',
    switchToRegister: 'Pas encore de compte ? Créer un compte',
    socialComingSoon: 'Cette connexion sera bientôt disponible.',
    errorTitle: 'Compte',
    successTitle: 'Succès',
    weakPassword: 'Le mot de passe doit contenir au moins 6 caractères.',
    confirmEmail: 'Votre compte a été créé. Veuillez vérifier votre e-mail.',
  },
  es: {
    languageName: 'Español',
    splashSubtitle: 'Su estilo personal, siempre con usted.',
    slides: [
      { title: 'Descubra su estilo.', subtitle: 'Looks seleccionados desde su armario.' },
      { title: 'Reinterprete su armario.', subtitle: 'Cada pieza, intencionalmente suya.' },
      { title: 'Luzca más refinado cada día.', subtitle: 'Calmo, elegante, solo suyo.' },
    ],
    continueCta: 'Continuar',
    skipCta: 'Omitir',
    authWelcomeTitle: 'Bienvenido',
    authWelcomeSubtitle: 'Su viaje de estilo comienza aquí.',
    continueWithEmail: 'Continuar con correo',
    continueWithGoogle: 'Continuar con Google',
    continueWithApple: 'Continuar con Apple',
    loginLink: 'Iniciar sesión',
    registerLink: 'Crear cuenta',
    languageLabel: 'Idioma',
    emailPlaceholder: 'Correo electrónico',
    passwordPlaceholder: 'Contraseña',
    loginCta: 'Iniciar sesión',
    registerCta: 'Crear cuenta',
    switchToLogin: '¿Ya tiene cuenta? Iniciar sesión',
    switchToRegister: '¿No tiene cuenta? Crear una',
    socialComingSoon: 'Este inicio de sesión estará disponible pronto.',
    errorTitle: 'Cuenta',
    successTitle: 'Éxito',
    weakPassword: 'La contraseña debe tener al menos 6 caracteres.',
    confirmEmail: 'Su cuenta fue creada. Verifique su correo electrónico.',
  },
  it: {
    languageName: 'Italiano',
    splashSubtitle: 'Il suo stile personale, sempre con lei.',
    slides: [
      { title: 'Scopra il suo stile.', subtitle: 'Look selezionati dal guardaroba.' },
      { title: 'Reinterpreti il guardaroba.', subtitle: 'Ogni capo, intenzionalmente suo.' },
      { title: 'Appaia più raffinata ogni giorno.', subtitle: 'Calma, elegante, solo sua.' },
    ],
    continueCta: 'Continua',
    skipCta: 'Salta',
    authWelcomeTitle: 'Benvenuto',
    authWelcomeSubtitle: 'Il suo percorso di stile inizia qui.',
    continueWithEmail: 'Continua con e-mail',
    continueWithGoogle: 'Continua con Google',
    continueWithApple: 'Continua con Apple',
    loginLink: 'Accedi',
    registerLink: 'Crea account',
    languageLabel: 'Lingua',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Password',
    loginCta: 'Accedi',
    registerCta: 'Crea account',
    switchToLogin: 'Ha già un account? Acceda',
    switchToRegister: 'Non ha un account? Lo crei',
    socialComingSoon: 'Questo accesso sarà disponibile a breve.',
    errorTitle: 'Account',
    successTitle: 'Successo',
    weakPassword: 'La password deve contenere almeno 6 caratteri.',
    confirmEmail: 'Il suo account è stato creato. Verifichi l’e-mail.',
  },
  ar: {
    languageName: 'العربية',
    splashSubtitle: 'أسلوبك الشخصي، دائماً معك.',
    slides: [
      { title: 'اكتشفي أسلوبك.', subtitle: 'إطلالات مختارة من خزانتك.' },
      { title: 'أعيدي تفسير خزانتك.', subtitle: 'كل قطعة، عن قصد لك.' },
      { title: 'اظهري أكثر رقياً كل يوم.', subtitle: 'هادئ، أنيق، لك وحدك.' },
    ],
    continueCta: 'متابعة',
    skipCta: 'تخطي',
    authWelcomeTitle: 'مرحباً',
    authWelcomeSubtitle: 'رحلة أسلوبك تبدأ هنا.',
    continueWithEmail: 'المتابعة بالبريد',
    continueWithGoogle: 'المتابعة مع Google',
    continueWithApple: 'المتابعة مع Apple',
    loginLink: 'تسجيل الدخول',
    registerLink: 'إنشاء حساب',
    languageLabel: 'اللغة',
    emailPlaceholder: 'البريد الإلكتروني',
    passwordPlaceholder: 'كلمة المرور',
    loginCta: 'تسجيل الدخول',
    registerCta: 'إنشاء حساب',
    switchToLogin: 'لديك حساب؟ سجّل الدخول',
    switchToRegister: 'ليس لديك حساب؟ أنشئ حساباً',
    socialComingSoon: 'طريقة الدخول هذه ستتوفر قريباً.',
    errorTitle: 'الحساب',
    successTitle: 'تم بنجاح',
    weakPassword: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    confirmEmail: 'تم إنشاء حسابك. يرجى تأكيد بريدك الإلكتروني.',
  },
  ru: {
    languageName: 'Русский',
    splashSubtitle: 'Ваш личный стиль всегда с вами.',
    slides: [
      { title: 'Откройте свой стиль.', subtitle: 'Образы из вашего гардероба.' },
      { title: 'Переосмыслите гардероб.', subtitle: 'Каждая вещь — осознанно ваша.' },
      { title: 'Выглядите изысканнее каждый день.', subtitle: 'Спокойно, элегантно, только вы.' },
    ],
    continueCta: 'Продолжить',
    skipCta: 'Пропустить',
    authWelcomeTitle: 'Добро пожаловать',
    authWelcomeSubtitle: 'Ваш стиль начинается здесь.',
    continueWithEmail: 'Продолжить с e-mail',
    continueWithGoogle: 'Продолжить с Google',
    continueWithApple: 'Продолжить с Apple',
    loginLink: 'Войти',
    registerLink: 'Создать аккаунт',
    languageLabel: 'Язык',
    emailPlaceholder: 'E-mail',
    passwordPlaceholder: 'Пароль',
    loginCta: 'Войти',
    registerCta: 'Создать аккаунт',
    switchToLogin: 'Уже есть аккаунт? Войти',
    switchToRegister: 'Нет аккаунта? Создать',
    socialComingSoon: 'Этот способ входа скоро будет доступен.',
    errorTitle: 'Аккаунт',
    successTitle: 'Готово',
    weakPassword: 'Пароль должен содержать не менее 6 символов.',
    confirmEmail: 'Ваш аккаунт создан. Подтвердите e-mail.',
  },
};
